### ISSUE TITLE
步骤二第三步：上传数据密钥配置中错误，在cli.yaml

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager-sdk#14]
conda虚拟环境，配置文件模板应该放到哪个目录下？我放在/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms/cli.yaml，后续命令一直出错，错误均是下面
(capsule-manager-sdk) root@--2-4778:~# cms_config init --host 172.16.1.115:8888
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk/bin/cms_config", line 8, in <module>
    sys.exit(cms_config())
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms_config.py", line 52, in cms_config
    config = yaml.load(f)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
    node = self.composer.get_single_node()
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 72, in get_single_node
    document = self.compose_document()
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 94, in compose_document
    node = self.compose_node(None, None)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 172, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 141, in check_event
    self.current_event = self.state()
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 546, in parse_block_sequence_entry
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block collection
  in "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms/cli.yaml", line 52, column 5
expected <block end>, but found '?'
  in "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms/cli.yaml", line 54, column 5
(capsule-manager-sdk) root@wangweifengqinjuann2-4778:~#

**Comment by zhongtianq** [comment]
您好，这部分文档今天晚些时候都会更新，到时候可能需要您下载最新版本的镜像和模板等。在新版里面，我们都用--config-file来自定义路径了，不必再纠结模板文件的路径问题。
