### ISSUE TITLE
 cms register-data-key上传数据密钥出现下面问题

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager-sdk#15]
(capsule-manager-sdk) root@3-4778:~/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms# cms register-data-keys
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk/lib/python3.10/site-packages/cli/cms.py", line 134, in register_data_keys
    data_key_b64 = data_key.get("data_key_b64")
AttributeError: 'str' object has no attribute 'get'

cli.yaml文件中
register_data_keys:
  data_keys:
      # (required) str
    resource_uri:
      - breast_cancer_alice
      # (required) str
    data_key_b64:
      - u+yq6SYZTANNuD9BoipXLw==

**Comment by zhongtianq** [comment]
您好，我们的版本更新了，最新的文档还没有同步到官方文档。今天晚些时候就会更新，到时候重新拉取一下最新的版本的镜像、模板，按照最新文档操作就可以了。
