### ISSUE TITLE
使用最新配置文件配置，仍然出如下错误

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager-sdk#16]
(capsule-manager-sdk1) root@wangweifengqinjuann2-4778:/home# cms --config-file /home/alice.yaml register-data-keys
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk1/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/cli/cms.py", line 134, in register_data_keys
    data_key_b64 = data_key.get("data_key_b64")
AttributeError: 'str' object has no attribute 'get'

配置文件中：
register_data_keys:
  data_keys:
      # (required) str
    resource_uri:
      - breast_cancer_alice
      # (required) str
    data_key_b64:
      - UAoh+/2Xgg7s+2Q2jaN4BA=
      
如果更改为
register_data_keys:
  data_keys:
    -
      # (required) str
    resource_uri: breast_cancer_alice
      # (required) str
    data_key_b64: UAoh+/2Xgg7s+2Q2jaN4BA==

出现错误
(capsule-manager-sdk1) root@wangweifengqinjuann2-4778:/home# cms --config-file /home/alice.yaml register-data-keys
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk1/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/cli/cms.py", line 55, in cms
    config = file.read_yaml_file(CONFIG_FILE)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/sdc/util/file.py", line 38, in read_yaml_file
    res = yaml.load(f)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
    node = self.composer.get_single_node()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 72, in get_single_node
    document = self.compose_document()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 94, in compose_document
    node = self.compose_node(None, None)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 211, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 128, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/composer.py", line 172, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 141, in check_event
    self.current_event = self.state()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 532, in parse_block_sequence_first_entry
    return self.parse_block_sequence_entry()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 540, in parse_block_sequence_entry
    return self.parse_block_node()
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 349, in parse_block_node
    return self.parse_node(block=True)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/ruamel/yaml/parser.py", line 516, in parse_node
    raise ParserError(
ruamel.yaml.parser.ParserError: while parsing a block node
expected the node content, but found '?'
  in "/home/alice.yaml", line 54, column 5

如下是指导文档内容是有”-“的
register_data_keys:
  data_keys:
    - 
      # (required) str
      resource_uri: breast_cancer_alice
      # (required) str
      data_key_b64: xxxx

**Comment by Chrisdehe** [comment]
重复问题 在https://github.com/secretflow/capsule-manager-sdk/issues/18中解决
