### ISSUE TITLE
上传密钥出现错误：*FileNotFoundError: [Errno 2] No such file or directory: 'alice.crt'**

### ISSUE THREAD

**Issue by qinjuana** [secretflow/capsule-manager-sdk#17]
配置.yaml如下
common:
  # (required) str, should be generated from cert
  party_id: "R6LXWH5TKM5KCWOUGA2OZKUZPW3HUV4WCYIPPNXBS52PGNAD5VLQ"
  # (required) List[str], cert chain files, the order is [cert, mid_ca_cert, root_ca_cert]
  # file num can be 1 if the cert is self-signed
  cert_pems_file:
    - alice.crt
  # (required) str, keep it be "RSA" here
  scheme: "RSA"
  # (required) str, file contains private key
  private_key_file: alice.key

register_data_keys:
  data_keys:
    -
      # (required) str
      resource_uri: breast_cancer_alice
      # (required) str
      data_key_b64: UAoh+/2Xgg7s+2Q2jaN4BA==

get_data_policys:

执行上传密钥出现错误：
(capsule-manager-sdk1) root@wangweifengqinjuann2-4778:~# cms --config-file /home/alice.yaml register-data-keys
Traceback (most recent call last):
  File "/root/miniconda3/envs/capsule-manager-sdk1/bin/cms", line 8, in <module>
    sys.exit(cms())
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/cli/cms.py", line 128, in register_data_keys
    cert_pems, private_key = read_rsa_keypair(common)
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/cli/cms.py", line 37, in read_rsa_keypair
    cert_pems_str.append(file.read_file(filename, "r"))
  File "/root/miniconda3/envs/capsule-manager-sdk1/lib/python3.10/site-packages/sdc/util/file.py", line 26, in read_file
    with open(file_path, mode) as f:
**FileNotFoundError: [Errno 2] No such file or directory: 'alice.crt'**
(capsule-manager-sdk1) root@wangweifengqinjuann2-4778:~#

**Comment by Chrisdehe** [comment]
重复的问题，在以下issue解决
https://github.com/secretflow/capsule-manager-sdk/issues/18
